#!/usr/bin/env bash

# Project TaskFile
#
# See https://github.com/adriancooney/Taskfile
#
# A Taskfile is a bash (or zsh etc.) script that follows
# a specific format. It's called Taskfile, sits in the root of your project
# (alongside your other project files) and contains the tasks to run your project.
#
# Example: ./run build.debug
#

# Enables easier access to common directories
# Usage: import "project:config"
COLLECTIONS="-collection:project=."

function test {
	odin test test/ -define:env=test -all-packages $@ ${COLLECTIONS}
}

# Builds docs using Gungnir
function docs {
	echo "TODO"
}

# Init git submodules inside deps
function deps.get {
	echo "TODO"
}

# Debug build for LLDB usage
# see: https://www.youtube.com/watch?v=wQJnJ1NNfQU
# see: https://github.com/epasveer/seer
function build.debug {
	mkdir -p _build
	odin strip-semicolon . $@ ${COLLECTIONS}
	odin check . $@ ${COLLECTIONS}
	odin build . -define:env=dev -strict-style -debug -out:_build/project $@ ${COLLECTIONS}
}

# Release build without debug symbols
function build.release {
	rm -rf bin
	mkdir -p bin
	odin strip-semicolon . $@ ${COLLECTIONS}
	odin check . $@ ${COLLECTIONS}
	odin build . -define:env=prod -warnings-as-errors -strict-style -out:bin/project ${COLLECTIONS}
}

# Runs the project binary
function project {
	# This file helps executing the project.odin
	# Run ./run build.debug before executing this
	# ./run project args
	_build/project $@
}

function project.release {
	# This file helps executing the project.odin
	# Run ./run build.release before executing this
	# ./run project.release args
	bin/project $@
}

# Formats the project with odin
# Ensure to update the collection inside hooks if more are added later
function format {
	odin strip-semicolon . $@ ${COLLECTIONS}
	odin check . $@ ${COLLECTIONS}
}

# Prints help
function help {
    echo "$0 <task> <args>"
    echo "Tasks:"
    compgen -A function | cat -n
}

function default {
    # Default task to execute
    help
}

#TIMEFORMAT="Task completed in %3lR"
TIMEFORMAT=""
time ${@:-default}
