#!/usr/bin/env bash

# Usage: ./draupnir <template> <directory>
# Example: ./draupnir full my-project
curl -L https://github.com/odin-arsenal/draupnir/archive/refs/heads/main.tar.gz -o templates.tar.gz
tar xzvf templates.tar.gz
mv draupnir-main/${1}-template ${2} 
rm -rf draupnir-main 
rm -rf templates.tar.gz 
cd ${2}