[book]
title = "Project Documentation"
description = "Example Project"
authors = ["Humans"]
language = "en"
multilingual = false
src = "src"

[output.html]
smart-punctuation = true
mathjax-support = false
site-url = "https://example.com/docs"
additional-css = ["./theme/styles/github-dark.min.css"]
git-repository-url = "https://example.com/repo.git"

[output.html.code.hidelines]
odin = "~"
